// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: api/proto/stock_hub.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User requests/responses
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_proto_stock_hub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stock_hub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_stock_hub_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_api_proto_stock_hub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stock_hub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_stock_hub_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_api_proto_stock_hub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stock_hub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_stock_hub_proto_rawDescGZIP(), []int{2}
}

func (x *GetUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUsersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResponse) Reset() {
	*x = GetUsersResponse{}
	mi := &file_api_proto_stock_hub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResponse) ProtoMessage() {}

func (x *GetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stock_hub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResponse.ProtoReflect.Descriptor instead.
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_stock_hub_proto_rawDescGZIP(), []int{3}
}

func (x *GetUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

// Order requests/responses
type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_api_proto_stock_hub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stock_hub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_stock_hub_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *StockOrder            `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_api_proto_stock_hub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stock_hub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_stock_hub_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderResponse) GetOrder() *StockOrder {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "open", "filled", "cancelled"
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersRequest) Reset() {
	*x = GetOrdersRequest{}
	mi := &file_api_proto_stock_hub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersRequest) ProtoMessage() {}

func (x *GetOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stock_hub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_stock_hub_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrdersRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetOrdersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetOrdersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*StockOrder          `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersResponse) Reset() {
	*x = GetOrdersResponse{}
	mi := &file_api_proto_stock_hub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersResponse) ProtoMessage() {}

func (x *GetOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stock_hub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_stock_hub_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrdersResponse) GetOrders() []*StockOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

type GetOrdersByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersByUserRequest) Reset() {
	*x = GetOrdersByUserRequest{}
	mi := &file_api_proto_stock_hub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByUserRequest) ProtoMessage() {}

func (x *GetOrdersByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stock_hub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByUserRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersByUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_stock_hub_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrdersByUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrdersByUserRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetOrdersByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*StockOrder          `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersByUserResponse) Reset() {
	*x = GetOrdersByUserResponse{}
	mi := &file_api_proto_stock_hub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByUserResponse) ProtoMessage() {}

func (x *GetOrdersByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stock_hub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByUserResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersByUserResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_stock_hub_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrdersByUserResponse) GetOrders() []*StockOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

// Message requests/responses
type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_api_proto_stock_hub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stock_hub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_stock_hub_proto_rawDescGZIP(), []int{10}
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_api_proto_stock_hub_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stock_hub_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_stock_hub_proto_rawDescGZIP(), []int{11}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type GetMessagesByClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesByClientRequest) Reset() {
	*x = GetMessagesByClientRequest{}
	mi := &file_api_proto_stock_hub_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesByClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesByClientRequest) ProtoMessage() {}

func (x *GetMessagesByClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stock_hub_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesByClientRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesByClientRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_stock_hub_proto_rawDescGZIP(), []int{12}
}

func (x *GetMessagesByClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GetMessagesByClientRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMessagesByClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesByClientResponse) Reset() {
	*x = GetMessagesByClientResponse{}
	mi := &file_api_proto_stock_hub_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesByClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesByClientResponse) ProtoMessage() {}

func (x *GetMessagesByClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stock_hub_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesByClientResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesByClientResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_stock_hub_proto_rawDescGZIP(), []int{13}
}

func (x *GetMessagesByClientResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_api_proto_stock_hub_proto protoreflect.FileDescriptor

const file_api_proto_stock_hub_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/stock_hub.proto\x12\tstock_hub\x1a\x15api/proto/model.proto\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"6\n" +
	"\x0fGetUserResponse\x12#\n" +
	"\x04user\x18\x01 \x01(\v2\x0f.stock_hub.UserR\x04user\"?\n" +
	"\x0fGetUsersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"9\n" +
	"\x10GetUsersResponse\x12%\n" +
	"\x05users\x18\x01 \x03(\v2\x0f.stock_hub.UserR\x05users\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\"?\n" +
	"\x10GetOrderResponse\x12+\n" +
	"\x05order\x18\x01 \x01(\v2\x15.stock_hub.StockOrderR\x05order\"p\n" +
	"\x10GetOrdersRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"B\n" +
	"\x11GetOrdersResponse\x12-\n" +
	"\x06orders\x18\x01 \x03(\v2\x15.stock_hub.StockOrderR\x06orders\"G\n" +
	"\x16GetOrdersByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"H\n" +
	"\x17GetOrdersByUserResponse\x12-\n" +
	"\x06orders\x18\x01 \x03(\v2\x15.stock_hub.StockOrderR\x06orders\"*\n" +
	"\x12GetMessagesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"E\n" +
	"\x13GetMessagesResponse\x12.\n" +
	"\bmessages\x18\x01 \x03(\v2\x12.stock_hub.MessageR\bmessages\"O\n" +
	"\x1aGetMessagesByClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"M\n" +
	"\x1bGetMessagesByClientResponse\x12.\n" +
	"\bmessages\x18\x01 \x03(\v2\x12.stock_hub.MessageR\bmessages2\xb3\x04\n" +
	"\x0fStockHubService\x12@\n" +
	"\aGetUser\x12\x19.stock_hub.GetUserRequest\x1a\x1a.stock_hub.GetUserResponse\x12C\n" +
	"\bGetUsers\x12\x1a.stock_hub.GetUsersRequest\x1a\x1b.stock_hub.GetUsersResponse\x12C\n" +
	"\bGetOrder\x12\x1a.stock_hub.GetOrderRequest\x1a\x1b.stock_hub.GetOrderResponse\x12F\n" +
	"\tGetOrders\x12\x1b.stock_hub.GetOrdersRequest\x1a\x1c.stock_hub.GetOrdersResponse\x12X\n" +
	"\x0fGetOrdersByUser\x12!.stock_hub.GetOrdersByUserRequest\x1a\".stock_hub.GetOrdersByUserResponse\x12L\n" +
	"\vGetMessages\x12\x1d.stock_hub.GetMessagesRequest\x1a\x1e.stock_hub.GetMessagesResponse\x12d\n" +
	"\x13GetMessagesByClient\x12%.stock_hub.GetMessagesByClientRequest\x1a&.stock_hub.GetMessagesByClientResponseB\x1bZ\x19stock_hub/api/proto;protob\x06proto3"

var (
	file_api_proto_stock_hub_proto_rawDescOnce sync.Once
	file_api_proto_stock_hub_proto_rawDescData []byte
)

func file_api_proto_stock_hub_proto_rawDescGZIP() []byte {
	file_api_proto_stock_hub_proto_rawDescOnce.Do(func() {
		file_api_proto_stock_hub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_stock_hub_proto_rawDesc), len(file_api_proto_stock_hub_proto_rawDesc)))
	})
	return file_api_proto_stock_hub_proto_rawDescData
}

var file_api_proto_stock_hub_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_stock_hub_proto_goTypes = []any{
	(*GetUserRequest)(nil),              // 0: stock_hub.GetUserRequest
	(*GetUserResponse)(nil),             // 1: stock_hub.GetUserResponse
	(*GetUsersRequest)(nil),             // 2: stock_hub.GetUsersRequest
	(*GetUsersResponse)(nil),            // 3: stock_hub.GetUsersResponse
	(*GetOrderRequest)(nil),             // 4: stock_hub.GetOrderRequest
	(*GetOrderResponse)(nil),            // 5: stock_hub.GetOrderResponse
	(*GetOrdersRequest)(nil),            // 6: stock_hub.GetOrdersRequest
	(*GetOrdersResponse)(nil),           // 7: stock_hub.GetOrdersResponse
	(*GetOrdersByUserRequest)(nil),      // 8: stock_hub.GetOrdersByUserRequest
	(*GetOrdersByUserResponse)(nil),     // 9: stock_hub.GetOrdersByUserResponse
	(*GetMessagesRequest)(nil),          // 10: stock_hub.GetMessagesRequest
	(*GetMessagesResponse)(nil),         // 11: stock_hub.GetMessagesResponse
	(*GetMessagesByClientRequest)(nil),  // 12: stock_hub.GetMessagesByClientRequest
	(*GetMessagesByClientResponse)(nil), // 13: stock_hub.GetMessagesByClientResponse
	(*User)(nil),                        // 14: stock_hub.User
	(*StockOrder)(nil),                  // 15: stock_hub.StockOrder
	(*Message)(nil),                     // 16: stock_hub.Message
}
var file_api_proto_stock_hub_proto_depIdxs = []int32{
	14, // 0: stock_hub.GetUserResponse.user:type_name -> stock_hub.User
	14, // 1: stock_hub.GetUsersResponse.users:type_name -> stock_hub.User
	15, // 2: stock_hub.GetOrderResponse.order:type_name -> stock_hub.StockOrder
	15, // 3: stock_hub.GetOrdersResponse.orders:type_name -> stock_hub.StockOrder
	15, // 4: stock_hub.GetOrdersByUserResponse.orders:type_name -> stock_hub.StockOrder
	16, // 5: stock_hub.GetMessagesResponse.messages:type_name -> stock_hub.Message
	16, // 6: stock_hub.GetMessagesByClientResponse.messages:type_name -> stock_hub.Message
	0,  // 7: stock_hub.StockHubService.GetUser:input_type -> stock_hub.GetUserRequest
	2,  // 8: stock_hub.StockHubService.GetUsers:input_type -> stock_hub.GetUsersRequest
	4,  // 9: stock_hub.StockHubService.GetOrder:input_type -> stock_hub.GetOrderRequest
	6,  // 10: stock_hub.StockHubService.GetOrders:input_type -> stock_hub.GetOrdersRequest
	8,  // 11: stock_hub.StockHubService.GetOrdersByUser:input_type -> stock_hub.GetOrdersByUserRequest
	10, // 12: stock_hub.StockHubService.GetMessages:input_type -> stock_hub.GetMessagesRequest
	12, // 13: stock_hub.StockHubService.GetMessagesByClient:input_type -> stock_hub.GetMessagesByClientRequest
	1,  // 14: stock_hub.StockHubService.GetUser:output_type -> stock_hub.GetUserResponse
	3,  // 15: stock_hub.StockHubService.GetUsers:output_type -> stock_hub.GetUsersResponse
	5,  // 16: stock_hub.StockHubService.GetOrder:output_type -> stock_hub.GetOrderResponse
	7,  // 17: stock_hub.StockHubService.GetOrders:output_type -> stock_hub.GetOrdersResponse
	9,  // 18: stock_hub.StockHubService.GetOrdersByUser:output_type -> stock_hub.GetOrdersByUserResponse
	11, // 19: stock_hub.StockHubService.GetMessages:output_type -> stock_hub.GetMessagesResponse
	13, // 20: stock_hub.StockHubService.GetMessagesByClient:output_type -> stock_hub.GetMessagesByClientResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_stock_hub_proto_init() }
func file_api_proto_stock_hub_proto_init() {
	if File_api_proto_stock_hub_proto != nil {
		return
	}
	file_api_proto_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_stock_hub_proto_rawDesc), len(file_api_proto_stock_hub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_stock_hub_proto_goTypes,
		DependencyIndexes: file_api_proto_stock_hub_proto_depIdxs,
		MessageInfos:      file_api_proto_stock_hub_proto_msgTypes,
	}.Build()
	File_api_proto_stock_hub_proto = out.File
	file_api_proto_stock_hub_proto_goTypes = nil
	file_api_proto_stock_hub_proto_depIdxs = nil
}
